### ISSUE TITLE
lib not working?

### ISSUE THREAD

**Issue by dlucidone** [alecperkey/react-jquery-datatables#1]
./~/react-jquery-datatables/~/react-dom/server.js
Module not found: Can't resolve 'react/lib/ReactDOMServer' in '/Users/Dlucidone/Desktop/crm_admin/CRM_Admin_Frontend/node_modules/react-jquery-datatables/node_modules/react-dom'

**Comment by TheAngryByrd** [comment]
+1

**Comment by fanatov37** [comment]
+1

**Comment by DavidNgugi** [comment]
Seems to be dead now

**Comment by skyfall174** [comment]
+1
Have anyone solve this problem ?

**Comment by jlgasparrini** [comment]
Same problem here!

**Comment by alecperkey** [comment]
OP, the original problem is something with versioning. 
If anyone continues to have this problem, please read https://github.com/facebook/react/issues/8588 and also post with the versions described in the package.json for each: react, reactdom, this library (use 1.0.0), and also npm version. 

Fiddle is working with the libraries in the html panel of the fiddle:
https://jsfiddle.net/alecperkey/69z2wepo/94911/

**Comment by alecperkey** [comment]
Also maybe this is helpful 
https://medium.com/@zbzzn/integrating-react-and-datatables-not-as-hard-as-advertised-f3364f395dfa
