### ISSUE TITLE
Uncaught Error: addComponentAsRefTo(...): Only a ReactOwner can have refs

### ISSUE THREAD

**Issue by fktrctqnjrfhtd** [alecperkey/react-jquery-datatables#3]
React 15.6.1
react-jquery-datatables 1.0.0

Uncaught Error: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded

What can be done to correct it?

Thank you in advance.

**Comment by alecperkey** [comment]
I think this is the same underlying problem as #2 so I'll close this
There are some links in there which may lead you to a solution/workaround

The jsfiddle demo is using 15.1.0
If you want to PR a fix, I'd be happy to merge.
https://jsfiddle.net/alecperkey/69z2wepo/94913/
